---
title: "TLS_inventory"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{TLS_inventory}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
For extracting information on tree level from close-range laser scanning (TLS or MLS), you can use the [`TreeLS`](https://www.rdocumentation.org/packages/TreeLS/versions/2.0.2) package. We will show a workflow on how to implement the output of TreeLS within TreeCompR.
```{r setup, message=FALSE,warning=FALSE, eval = FALSE}
library(TreeCompR)
library(TreeLS)
```

```{r segment-TLS, eval = FALSE}
    file <- system.file("extdata", "pine_plot.laz", package="TreeLS")
    tls <- readTLS(file)
    tls_norm <- tlsNormalize(tls, keep_ground = F)
    thin <- tlsSample(tls_norm, smp.voxelize(0.01))
    map <- treeMap(thin, map.hough(min_density = 0.1), 0)
    tls_t <- treePoints(tls_norm, map, trp.crop())
    tls_stem <- stemPoints(tls_t, stm.hough())
    inv <- tlsInventory(tls_stem, d_method=shapeFit(shape='circle', algorithm = 'ransac'))
    inv$dbh <- (inv$Radius *2)
```

## Use extracted tree information within TreeCompR

```{r calculate-CI, message=FALSE,warning=FALSE, fig.height= 4, fig.width=7, eval = FALSE}
inventory <- read_inv(inv_source = inv, dbh_unit = "m", height_unit = "m")
targets <- define_target(inv = inventory, target_source = "buff_edge", radius = 2)
plot_target(targets)
compete_inv(inventory, target_source = "buff_edge", radius = 2, method = "all_methods")
```

